### ISSUE TITLE
Error running braker3 output sorted GTF

### ISSUE THREAD

**Issue by LliliansCalvo** [danilotat/UTR_add_extend_GTF#3]
Hello, 

Thanks for this script, its great!
However I am having trouble with an error I don't understand. 
I have added here the command and a snippet of the GTF file and the offending 'g1.t1' transcript 
Thanks!

```
./client.py --input sorted_2024.04.08_braker_hym_old_annotation_proteins_braker.gtf  --output sorted_2024.04.08_braker_hym_old_annotation_proteins_braker.gtf_EXT.gtf --length 1000 --min_dist 20 --logs extension.log
----------------------------------------
Starting to parse sorted_2024.04.08_braker_hym_old_annotation_proteins_braker.gtf
----------------------------------------
Processing chromosome JAPIVC010000001.1
Traceback (most recent call last):
  File "./client.py", line 22, in <module>
    chromosome_wise(args.input, args.output, args.length, int(args.min_dist), args.logs)
  File "/work/FAC/FBM/UTR_add_extend_GTF/gtftools/workers.py", line 383, in chromosome_wise
    other_entries(entry, transcripts)
  File "/work/FAC/FBM/UTR_add_extend_GTF/gtftools/workers.py", line 44, in other_entries
    transcript_collection[transcript_id]._add_startcodon(entry)
KeyError: 'g1.t1'

head sorted_2024.04.08_braker_hym_old_annotation_proteins_braker.gtf
JAPIVC010000001.1	AUGUSTUS	start_codon	7276	7278	.	+	0	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	CDS	7276	7447	0.71	+	0	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	exon	7276	7447	.	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	gene	7276	12416	.	+	.	g1
JAPIVC010000001.1	AUGUSTUS	transcript	7276	12416	0.71	+	.	g1.t1
JAPIVC010000001.1	AUGUSTUS	intron	7448	7614	1	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	CDS	7615	7724	1	+	2	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	exon	7615	7724	.	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	intron	7725	8920	1	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	CDS	8921	9011	1	+	0	transcript_id "g1.t1"; gene_id "g1";


grep -e "g1.t1" sorted_2024.04.08_braker_hym_old_annotation_proteins_braker.gtf
JAPIVC010000001.1	AUGUSTUS	start_codon	7276	7278	.	+	0	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	CDS	7276	7447	0.71	+	0	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	exon	7276	7447	.	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	transcript	7276	12416	0.71	+	.	g1.t1
JAPIVC010000001.1	AUGUSTUS	intron	7448	7614	1	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	CDS	7615	7724	1	+	2	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	exon	7615	7724	.	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	intron	7725	8920	1	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	CDS	8921	9011	1	+	0	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	exon	8921	9011	.	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	intron	9012	9329	1	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	CDS	9330	9524	1	+	2	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	exon	9330	9524	.	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	intron	9525	10319	1	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	CDS	10320	10386	1	+	2	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	exon	10320	10386	.	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	intron	10387	10548	1	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	CDS	10549	10675	1	+	1	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	exon	10549	10675	.	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	intron	10676	10806	1	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	CDS	10807	10885	1	+	0	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	exon	10807	10885	.	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	intron	10886	10981	1	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	CDS	10982	11094	1	+	2	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	exon	10982	11094	.	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	intron	11095	11231	1	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	CDS	11232	11469	1	+	0	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	exon	11232	11469	.	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	intron	11470	12078	1	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	CDS	12079	12416	1	+	2	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	exon	12079	12416	.	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	stop_codon	12414	12416	.	+	0	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	gene	7276	12416	.	+	.	g1
```

**Comment by danilotat** [comment]
Hi @LliliansCalvo , could you try sorting by the 4th column in ascending order and by the 5th in descending order? Like this 

`sort -t$'\t' -k1,1 -k4,4n -k5,5r input.gtf > input_sorted.gtf `

I guess the problem is due to the fact that features of the gene `g1` are parsed before the gene entry.

**Comment by LliliansCalvo** [comment]
Thanks for the fast reply. 
ERROR persist.
```
 ./client.py --input ss_sorted_2024.04.08_braker_hym_old_annotation_proteins_braker.gtf --output sorted_2024.04.08_braker_hym_old_annotation_proteins_braker.gtf_EXT.gtf --length 1000 --min_dist 20 --logs extension.log
----------------------------------------
Starting to parse ss_sorted_2024.04.08_braker_hym_old_annotation_proteins_braker.gtf
----------------------------------------
Processing chromosome JAPIVC010000001.1
Traceback (most recent call last):
  File "./client.py", line 22, in <module>
    chromosome_wise(args.input, args.output, args.length, int(args.min_dist), args.logs)
  File "/work/FAC/FBM/UTR_add_extend_GTF/gtftools/workers.py", line 383, in chromosome_wise
    other_entries(entry, transcripts)
  File "/work/FAC/FBM/UTR_add_extend_GTF/gtftools/workers.py", line 38, in other_entries
    transcript_collection[transcript_id]._add_cds(entry)
KeyError: 'g1.t1'

head ss_sorted_2024.04.08_braker_hym_old_annotation_proteins_braker.gtf 
JAPIVC010000001.1	AUGUSTUS	CDS	7276	7447	0.71	+	0	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	exon	7276	7447	.	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	start_codon	7276	7278	.	+	0	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	gene	7276	12416	.	+	.	g1
JAPIVC010000001.1	AUGUSTUS	transcript	7276	12416	0.71	+	.	g1.t1
JAPIVC010000001.1	AUGUSTUS	intron	7448	7614	1	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	CDS	7615	7724	1	+	2	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	exon	7615	7724	.	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	intron	7725	8920	1	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	CDS	8921	9011	1	+	0	transcript_id "g1.t1"; gene_id "g1";

grep -e 'gene_id "g1"' ss_sorted_2024.04.08_braker_hym_old_annotation_proteins_braker.gtf 
JAPIVC010000001.1	AUGUSTUS	CDS	7276	7447	0.71	+	0	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	exon	7276	7447	.	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	start_codon	7276	7278	.	+	0	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	intron	7448	7614	1	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	CDS	7615	7724	1	+	2	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	exon	7615	7724	.	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	intron	7725	8920	1	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	CDS	8921	9011	1	+	0	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	exon	8921	9011	.	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	intron	9012	9329	1	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	CDS	9330	9524	1	+	2	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	exon	9330	9524	.	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	intron	9525	10319	1	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	CDS	10320	10386	1	+	2	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	exon	10320	10386	.	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	intron	10387	10548	1	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	CDS	10549	10675	1	+	1	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	exon	10549	10675	.	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	intron	10676	10806	1	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	CDS	10807	10885	1	+	0	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	exon	10807	10885	.	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	intron	10886	10981	1	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	CDS	10982	11094	1	+	2	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	exon	10982	11094	.	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	intron	11095	11231	1	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	CDS	11232	11469	1	+	0	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	exon	11232	11469	.	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	intron	11470	12078	1	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	CDS	12079	12416	1	+	2	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	exon	12079	12416	.	+	.	transcript_id "g1.t1"; gene_id "g1";
JAPIVC010000001.1	AUGUSTUS	stop_codon	12414	12416	.	+	0	transcript_id "g1.t1"; gene_id "g1";

```

**Comment by LliliansCalvo** [comment]
I also tried with another GTF from a different source and i still get an error:

```
./client.py --input sorted_evmodPasaWccl_w_orthologs.gtf --output sorted_evmodPasaWccl_w_orthologs_EXT.gtf --length 1000 --min_dist 20 --logs extension.log
----------------------------------------
Starting to parse sorted_evmodPasaWccl_w_orthologs.gtf
----------------------------------------
Processing chromosome ctg1
Traceback (most recent call last):
  File "./client.py", line 22, in <module>
    chromosome_wise(args.input, args.output, args.length, int(args.min_dist), args.logs)
  File "/work/FAC/FBM/UTR_add_extend_GTF/gtftools/workers.py", line 383, in chromosome_wise
    other_entries(entry, transcripts)
  File "/work/FAC/FBM/UTR_add_extend_GTF/gtftools/workers.py", line 38, in other_entries
    transcript_collection[transcript_id]._add_cds(entry)
KeyError: 'evm.model.ctg1.1'


head  sorted_evmodPasaWccl_w_orthologs.gtf
ctg1	.	CDS	7267	7447	.	+	0	gene_id "evm.model.ctg1.1"; transcript_id "evm.model.ctg1.1"; Ortholog_ID "A0A158NZF7_ATTCE"
ctg1	.	exon	7267	7447	.	+	.	gene_id "evm.model.ctg1.1"; transcript_id "evm.model.ctg1.1"; Ortholog_ID "A0A158NZF7_ATTCE"
ctg1	.	CDS	7615	7724	.	+	2	gene_id "evm.model.ctg1.1"; transcript_id "evm.model.ctg1.1"; Ortholog_ID "A0A158NZF7_ATTCE"
ctg1	.	exon	7615	7724	.	+	.	gene_id "evm.model.ctg1.1"; transcript_id "evm.model.ctg1.1"; Ortholog_ID "A0A158NZF7_ATTCE"
ctg1	.	CDS	8921	9011	.	+	0	gene_id "evm.model.ctg1.1"; transcript_id "evm.model.ctg1.1"; Ortholog_ID "A0A158NZF7_ATTCE"
ctg1	.	exon	8921	9011	.	+	.	gene_id "evm.model.ctg1.1"; transcript_id "evm.model.ctg1.1"; Ortholog_ID "A0A158NZF7_ATTCE"
ctg1	.	CDS	9330	9524	.	+	2	gene_id "evm.model.ctg1.1"; transcript_id "evm.model.ctg1.1"; Ortholog_ID "A0A158NZF7_ATTCE"
ctg1	.	exon	9330	9524	.	+	.	gene_id "evm.model.ctg1.1"; transcript_id "evm.model.ctg1.1"; Ortholog_ID "A0A158NZF7_ATTCE"
ctg1	.	CDS	10320	10386	.	+	2	gene_id "evm.model.ctg1.1"; transcript_id "evm.model.ctg1.1"; Ortholog_ID "A0A158NZF7_ATTCE"
ctg1	.	exon	10320	10386	.	+	.	gene_id "evm.model.ctg1.1"; transcript_id "evm.model.ctg1.1"; Ortholog_ID "A0A158NZF7_ATTCE"

grep -e 'gene_id "evm.model.ctg1.1"' sorted_evmodPasaWccl_w_orthologs.gtf
ctg1	.	CDS	7267	7447	.	+	0	gene_id "evm.model.ctg1.1"; transcript_id "evm.model.ctg1.1"; Ortholog_ID "A0A158NZF7_ATTCE"
ctg1	.	exon	7267	7447	.	+	.	gene_id "evm.model.ctg1.1"; transcript_id "evm.model.ctg1.1"; Ortholog_ID "A0A158NZF7_ATTCE"
ctg1	.	CDS	7615	7724	.	+	2	gene_id "evm.model.ctg1.1"; transcript_id "evm.model.ctg1.1"; Ortholog_ID "A0A158NZF7_ATTCE"
ctg1	.	exon	7615	7724	.	+	.	gene_id "evm.model.ctg1.1"; transcript_id "evm.model.ctg1.1"; Ortholog_ID "A0A158NZF7_ATTCE"
ctg1	.	CDS	8921	9011	.	+	0	gene_id "evm.model.ctg1.1"; transcript_id "evm.model.ctg1.1"; Ortholog_ID "A0A158NZF7_ATTCE"
ctg1	.	exon	8921	9011	.	+	.	gene_id "evm.model.ctg1.1"; transcript_id "evm.model.ctg1.1"; Ortholog_ID "A0A158NZF7_ATTCE"
ctg1	.	CDS	9330	9524	.	+	2	gene_id "evm.model.ctg1.1"; transcript_id "evm.model.ctg1.1"; Ortholog_ID "A0A158NZF7_ATTCE"
ctg1	.	exon	9330	9524	.	+	.	gene_id "evm.model.ctg1.1"; transcript_id "evm.model.ctg1.1"; Ortholog_ID "A0A158NZF7_ATTCE"
ctg1	.	CDS	10320	10386	.	+	2	gene_id "evm.model.ctg1.1"; transcript_id "evm.model.ctg1.1"; Ortholog_ID "A0A158NZF7_ATTCE"
ctg1	.	exon	10320	10386	.	+	.	gene_id "evm.model.ctg1.1"; transcript_id "evm.model.ctg1.1"; Ortholog_ID "A0A158NZF7_ATTCE"
ctg1	.	CDS	10549	10675	.	+	1	gene_id "evm.model.ctg1.1"; transcript_id "evm.model.ctg1.1"; Ortholog_ID "A0A158NZF7_ATTCE"
ctg1	.	exon	10549	10675	.	+	.	gene_id "evm.model.ctg1.1"; transcript_id "evm.model.ctg1.1"; Ortholog_ID "A0A158NZF7_ATTCE"
ctg1	.	CDS	10807	10885	.	+	0	gene_id "evm.model.ctg1.1"; transcript_id "evm.model.ctg1.1"; Ortholog_ID "A0A158NZF7_ATTCE"
ctg1	.	exon	10807	10885	.	+	.	gene_id "evm.model.ctg1.1"; transcript_id "evm.model.ctg1.1"; Ortholog_ID "A0A158NZF7_ATTCE"
ctg1	.	CDS	10982	11094	.	+	2	gene_id "evm.model.ctg1.1"; transcript_id "evm.model.ctg1.1"; Ortholog_ID "A0A158NZF7_ATTCE"
ctg1	.	exon	10982	11094	.	+	.	gene_id "evm.model.ctg1.1"; transcript_id "evm.model.ctg1.1"; Ortholog_ID "A0A158NZF7_ATTCE"
ctg1	.	CDS	11232	11469	.	+	0	gene_id "evm.model.ctg1.1"; transcript_id "evm.model.ctg1.1"; Ortholog_ID "A0A158NZF7_ATTCE"
ctg1	.	exon	11232	11469	.	+	.	gene_id "evm.model.ctg1.1"; transcript_id "evm.model.ctg1.1"; Ortholog_ID "A0A158NZF7_ATTCE"
ctg1	.	exon	12079	12512	.	+	.	gene_id "evm.model.ctg1.1"; transcript_id "evm.model.ctg1.1"; Ortholog_ID "A0A158NZF7_ATTCE"
ctg1	.	CDS	12079	12416	.	+	2	gene_id "evm.model.ctg1.1"; transcript_id "evm.model.ctg1.1"; Ortholog_ID "A0A158NZF7_ATTCE"

```

**Comment by danilotat** [comment]
Okay, thanks for the detailed issue. I’m out of office so I’d likely look for it at the beginning of the next week.

**Comment by LliliansCalvo** [comment]
So I have been manipulating a bit the GTF file so it looks more like the required ones and now I just dont even get an error anymore but an empty output. Leaving it here for when you are back. 
```
 ./client.py --i output.gtf  --o mod_out.gtf  --length 1000 --min_dist 20
----------------------------------------
Starting to parse output.gtf
----------------------------------------
Processing chromosome ctg23
ctg23	.	gene	111406	138967	.	+	.	gene_id "evm.model.ctg23.2"; gene_biotype "protein_coding"


# I added a gene entry to my GTF file as well as reorganized the last columns to have always gene_id coming before transcript_id. I also added gene_biotype "protein_coding" to every gene entry. 

head output.gtf
ctg23	.	gene	110282	112162	.	+	.	gene_id "evm.model.ctg23.1"; gene_biotype "protein_coding";
ctg23	.	transcript	110282	112162	.	+	.	gene_id "evm.model.ctg23.1";transcript_id "evm.model.ctg23.1";
ctg23	.	exon	110282	110311	.	+	.	gene_id "evm.model.ctg23.1";transcript_id "evm.model.ctg23.1";
ctg23	.	exon	110590	110741	.	+	.	gene_id "evm.model.ctg23.1";transcript_id "evm.model.ctg23.1";
ctg23	.	exon	111154	112162	.	+	.	gene_id "evm.model.ctg23.1";transcript_id "evm.model.ctg23.1";
ctg23	.	CDS	110309	110311	.	+	0	gene_id "evm.model.ctg23.1";transcript_id "evm.model.ctg23.1";
ctg23	.	CDS	110590	110741	.	+	0	gene_id "evm.model.ctg23.1";transcript_id "evm.model.ctg23.1";
ctg23	.	CDS	111154	111391	.	+	1	gene_id "evm.model.ctg23.1";transcript_id "evm.model.ctg23.1";
ctg23	.	gene	111406	131736	.	+	.	 gene_id "evm.model.ctg23.2"; gene_biotype "protein_coding";
ctg23	.	transcript	111406	131736	.	+	.	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2";
(llilians_env) [lcalvogo@curnagl UTR_add_extend_GTF]$ head -n 60 output.gtf 
ctg23	.	gene	110282	112162	.	+	.	gene_id "evm.model.ctg23.1"; gene_biotype "protein_coding";
ctg23	.	transcript	110282	112162	.	+	.	gene_id "evm.model.ctg23.1";transcript_id "evm.model.ctg23.1";
ctg23	.	exon	110282	110311	.	+	.	gene_id "evm.model.ctg23.1";transcript_id "evm.model.ctg23.1";
ctg23	.	exon	110590	110741	.	+	.	gene_id "evm.model.ctg23.1";transcript_id "evm.model.ctg23.1";
ctg23	.	exon	111154	112162	.	+	.	gene_id "evm.model.ctg23.1";transcript_id "evm.model.ctg23.1";
ctg23	.	CDS	110309	110311	.	+	0	gene_id "evm.model.ctg23.1";transcript_id "evm.model.ctg23.1";
ctg23	.	CDS	110590	110741	.	+	0	gene_id "evm.model.ctg23.1";transcript_id "evm.model.ctg23.1";
ctg23	.	CDS	111154	111391	.	+	1	gene_id "evm.model.ctg23.1";transcript_id "evm.model.ctg23.1";
ctg23	.	gene	111406	131736	.	+	.	 gene_id "evm.model.ctg23.2"; gene_biotype "protein_coding";
ctg23	.	transcript	111406	131736	.	+	.	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2";
ctg23	.	exon	111406	111428	.	+	.	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2";
ctg23	.	exon	112014	113460	.	+	.	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2";
ctg23	.	exon	126032	126179	.	+	.	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2";
ctg23	.	exon	127309	128116	.	+	.	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2";
ctg23	.	exon	128309	128554	.	+	.	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2";
ctg23	.	exon	128963	129156	.	+	.	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2";
ctg23	.	exon	129609	131736	.	+	.	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2";
ctg23	.	CDS	113364	113460	.	+	0	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2";
ctg23	.	CDS	126032	126179	.	+	2	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2";
ctg23	.	CDS	127309	128116	.	+	1	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2";
ctg23	.	CDS	128309	128554	.	+	0	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2";
ctg23	.	CDS	128963	129156	.	+	0	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2";
ctg23	.	CDS	129609	129771	.	+	1	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2";
ctg23	.	gene	111406	138967	.	+	.	 gene_id "evm.model.ctg23.2"; gene_biotype "protein_coding";
ctg23	.	transcript	111406	138967	.	+	.	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2.1.5d03f979";
ctg23	.	exon	111406	111428	.	+	.	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2.1.5d03f979";
ctg23	.	exon	112014	113460	.	+	.	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2.1.5d03f979";
ctg23	.	exon	126032	126179	.	+	.	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2.1.5d03f979";
ctg23	.	exon	127309	128116	.	+	.	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2.1.5d03f979";
ctg23	.	exon	128309	128554	.	+	.	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2.1.5d03f979";
ctg23	.	exon	128963	129156	.	+	.	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2.1.5d03f979";
ctg23	.	exon	129609	129712	.	+	.	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2.1.5d03f979";
ctg23	.	exon	132183	132310	.	+	.	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2.1.5d03f979";
ctg23	.	exon	132663	136126	.	+	.	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2.1.5d03f979";
ctg23	.	exon	138075	138967	.	+	.	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2.1.5d03f979";
ctg23	.	CDS	113364	113460	.	+	0	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2.1.5d03f979";
ctg23	.	CDS	126032	126179	.	+	2	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2.1.5d03f979";
ctg23	.	CDS	127309	128116	.	+	1	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2.1.5d03f979";
ctg23	.	CDS	128309	128554	.	+	0	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2.1.5d03f979";
ctg23	.	CDS	128963	129156	.	+	0	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2.1.5d03f979";
ctg23	.	CDS	129609	129712	.	+	1	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2.1.5d03f979";
ctg23	.	CDS	132183	132310	.	+	2	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2.1.5d03f979";
ctg23	.	CDS	132663	132767	.	+	0	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2.1.5d03f979";
ctg23	.	gene	116517	131736	.	+	.	 gene_id "evm.model.ctg23.2"; gene_biotype "protein_coding";
ctg23	.	transcript	116517	131736	.	+	.	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2.4.5d03f97a";
ctg23	.	exon	116517	117386	.	+	.	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2.4.5d03f97a";
ctg23	.	exon	126032	126179	.	+	.	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2.4.5d03f97a";
ctg23	.	exon	127309	128116	.	+	.	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2.4.5d03f97a";
ctg23	.	exon	128309	128554	.	+	.	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2.4.5d03f97a";
ctg23	.	exon	128963	129156	.	+	.	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2.4.5d03f97a";
ctg23	.	exon	129609	131736	.	+	.	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2.4.5d03f97a";
ctg23	.	CDS	117344	117386	.	+	0	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2.4.5d03f97a";
ctg23	.	CDS	126032	126179	.	+	2	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2.4.5d03f97a";
ctg23	.	CDS	127309	128116	.	+	1	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2.4.5d03f97a";
ctg23	.	CDS	128309	128554	.	+	0	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2.4.5d03f97a";
ctg23	.	CDS	128963	129156	.	+	0	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2.4.5d03f97a";
ctg23	.	CDS	129609	129771	.	+	1	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2.4.5d03f97a";
ctg23	.	gene	120096	131736	.	+	.	 gene_id "evm.model.ctg23.2"; gene_biotype "protein_coding";
ctg23	.	transcript	120096	131736	.	+	.	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2.2.5d03f97a";
ctg23	.	exon	120096	120591	.	+	.	gene_id "evm.model.ctg23.2";transcript_id "evm.model.ctg23.2.2.5d03f97a";
```

**Comment by danilotat** [comment]
Hi @LliliansCalvo , thanks for reporting the issue. I've pushed a commit to address the issue, being able to process your last input. Regarding the last column, there's no order to be followed, as they're stored and accessed as a dictionary. The `protein_coding` biotype is accessed to determine which transcripts may be interested by the UTR adding and extension: so add it only where you're sure to have a translated entry.

**Comment by danilotat** [comment]
Closing this for inactivity. Feel free to reopen if needed.
